
class NoTargetConfig:
    def __init__(
        self,
        act='relu',
        z_dim=16,
        max_atom=45,
        lambda_gp=1,
        dim=128,
        depth=1,
        heads=8,
        dec_depth=1,
        dec_heads=8,
        dec_dim=128,
        mlp_ratio=3,
        warm_up_steps=0,
        dis_select='mlp',
        init_type='normal',
        dropout=0.,
        dec_dropout=0.,
        n_critic=1,
        # beta1=0.9,
        # beta2=0.999,
        # resume_iters=None,
        clipping_value=2,
        features=False,
        # test_iters=10_000,
        # num_test_epoch=30_000,
        # inference_sample_num=1000,
        # num_workers=1,
        # mode="inference",
        # inference_iterations=100,
        # inf_batch_size=1,
        # protein_data_dir='data/akt',
        # drug_index='data/drug_smiles.index',
        # drug_data_dir='data/akt',
        # mol_data_dir='data',
        # log_dir='experiments/logs',
        # model_save_dir='experiments/models',
        # inference_model="",
        # sample_dir='experiments/samples',
        # result_dir="experiments/tboard_output",
        # dataset_file="chembl45_train.pt",
        # drug_dataset_file="akt_train.pt",
        # raw_file='data/chembl_train.smi',
        # drug_raw_file="data/akt_train.smi",
        # inf_dataset_file="chembl45_test.pt",
        # inf_drug_dataset_file='akt_test.pt',
        # inf_raw_file='data/chembl_test.smi',
        # inf_drug_raw_file="data/akt_test.smi",
        # log_sample_step=1000,
        # set_seed=True,
        # seed=1,
        # resume=False,
        # resume_epoch=None,
        # resume_iter=None,
        # resume_directory=None,
        vertexes=None
    ):
        self.act = act
        self.z_dim = z_dim
        # self.max_atom = max_atom
        self.lambda_gp = lambda_gp
        self.dim = dim
        self.depth = depth
        self.heads = heads
        self.dec_depth = dec_depth
        self.dec_heads = dec_heads
        self.dec_dim = dec_dim
        self.mlp_ratio = mlp_ratio
        self.warm_up_steps = warm_up_steps
        # self.init_type = init_type
        # self.batch_size = batch_size
        # self.epoch = epoch
        # self.g_lr = g_lr
        # self.d_lr = d_lr
        # self.g2_lr = g2_lr
        # self.d2_lr = d2_lr
        self.dropout = dropout
        self.dec_dropout = dec_dropout
        self.n_critic = n_critic
        # self.beta1 = beta1
        # self.beta2 = beta2
        # self.resume_iters = resume_iters
        self.clipping_value = clipping_value
        self.features = features
        self.vertexes = vertexes